
public class ExceptionCentral {
	
	public ExceptionCentral() {
		// TODO Auto-generated constructor stub
	}

	static int firstMethod() throws ArithmeticException {
		int numberThatExists = 4 / 0;
		
		return numberThatExists;
	}
	
	@SuppressWarnings("null")
	static char secondMethod() throws NullPointerException {
		String thisShouldWork = null;
		
		return thisShouldWork.charAt(0);
	}
	
	static void thirdMethod() {
		int[] array = new int[4];
		
		try {
			for (int i = 0; i <= array.length; i++) {
				int x = 43 * array[i];
			}
		}
		catch (ArrayIndexOutOfBoundsException e){
			System.out.println("Out of bounds, STUPID!");
			e.printStackTrace();
		}
	}
	
	static void fourthMethod(int[] array) {
		
		try {
			for (int i = 0; i <= array.length; i++) {
				try {
					int printThis = array[i];
					
					System.out.println(printThis);
				}
				catch(NullPointerException e) {
					System.out.println("Null value. Geez. Why are you so dumb?");
				}
			}
		}
		catch (NullPointerException e) {
			System.out.println("NULL ARRAY DUMMY!");
		}
		
	}
	
}

